AllCops:
  Exclude:
    - 'db/seeds.rb'
    - 'db/schema.rb'
    - 'doc/**/*'
    - 'frontend/**/*'
    - 'bundle/**/*'
    - 'config/puma/*'
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  TargetRubyVersion: 2.5

Rails:
  Enabled: true

Rails/InverseOf:
  Exclude:
    - 'app/models/attendance.rb'
    - 'app/models/request.rb'

Rails/NotNullColumn:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'app/controllers/auth_controller.rb'
    - 'db/migrate/20180514080341_change_column_attendance_day_requests.rb'

Rails/ReversibleMigration:
  Exclude:
    - 'db/migrate/20180511092012_remove_attendance_id_of_requests.rb'
    - 'db/migrate/20180511093242_drop_table_read_requests.rb'

Rails/CreateTableWithTimestamps:
  Enabled: false

Style/GuardClause:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - 'spec/supports/json_response_helper.rb'

Style/StructInheritance:
  Exclude:
      - 'app/policies/application_policy.rb'

Rails/HasManyOrHasOneDependent:
  Exclude:
      - 'app/models/admin.rb'

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 200

Metrics/ClassLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/PerceivedComplexity:
  Max: 8

Metrics/AbcSize:
  Max: 25

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false


Style/Lambda:
  EnforcedStyle: literal

Style/NumericLiterals:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: no_braces

Bundler/OrderedGems:
  Enabled: false
