export default {
  changePassword: {
    title: 'Your password is not secured',
    description: "You are using password generated by system, it's not secured. Please change your password as soon as possible"
  }
}
