# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/Projects/1punch-api
    docker:
       - image: circleci/ruby:2.4.2-node
         environment:
           PGHOST: 127.0.0.1
           PGUSER: punch
           RAILS_ENV: test
       - image: circleci/postgres:10-alpine-ram
         environment:
           POSTGRES_USER: punch
           POSTGRES_DB: 1punch_test
           POSTGRES_PASSWORD: ''

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - 1punch-api-v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - 1punch-api-v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: 1punch-api-v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: setup config files
          command: |
            cp config/database.yml.sample config/database.yml
            cp config/secrets.yml.sample config/secrets.yml
      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            bundle exec rspec --format progress \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              spec

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
