// header-announcements
export const RECEIVE_HEADER_ANNOUNCEMENTS = 'RECEIVE_HEADER_ANNOUNCEMENTS'

// announcements
export const RECEIVE_ANNOUNCEMENTS = 'RECEIVE_ANNOUNCEMENTS'

// announcement
export const RECEIVE_ANNOUNCEMENT = 'RECEIVE_ANNOUNCEMENT'

// attendances
export const RECEIVE_ATTENDANCES = 'RECEIVE_ATTENDANCES'

// punch
export const PUNCH_IN = 'PUNCH_IN'
export const PUNCH_OUT = 'PUNCH_OUT'

// company-users
export const FETCH_USERS = 'FETCH_USERS'

// company-deparments
export const FETCH_DEPARTMENTS = 'FETCH_DEPARTMENTS'
export const ADD_DEPARTMENT = 'ADD_DEPARTMENT'
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT'
export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT'

// company-business-days
export const FETCH_BUSINESS_DAYS = 'FETCH_BUSINESS_DAYS'
export const ADD_BUSINESS_DAY = 'ADD_BUSINESS_DAY'
export const DELETE_BUSINESS_DAY = 'DELETE_BUSINESS_DAY'
export const UPDATE_BUSINESS_DAY = 'UPDATE_BUSINESS_DAY'

// company-allowed_ips
export const FETCH_IPS = 'FETCH_IPS'
export const CREATE_IP = 'CREATE_IPS'
export const UPDATE_IP = 'UPDATE_IPS'
export const DELETE_IP = 'DELETE_IPS'
export const UPDATE_IP_ERRORS = 'UPDATE_REQUEST_ERRORS'
export const CLEAR_IP_ERRORS = 'CLEAR_REQUEST_ERRORS'

// company-holidays
export const FETCH_CUSTOM_HOLIDAYS = 'FETCH_CUSTOM_HOLIDAYS'
export const CREATE_CUSTOM_HOLIDAY = 'CREATE_CUSTOM_HOLIDAY'
export const UPDATE_CUSTOM_HOLIDAY = 'UPDATE_CUSTOM_HOLIDAY'
export const DELETE_CUSTOM_HOLIDAY = 'DELETE_CUSTOM_HOLIDAY'
export const UPDATE_CUSTOM_HOLIDAY_ERRORS = 'UPDATE_CUSTOM_HOLIDAY_ERRORS'
export const CLEAR_CUSTOM_HOLIDAY_ERRORS = 'CLEAR_CUSTOM_HOLIDAY_ERRORS'

// user-sessions
export const FETCH_SESSIONS = 'FETCH_SESSIONS'
export const DELETE_SESSION = 'DELETE_SESSION'
export const UPDATE_SESSION_ERRORS = 'UPDATE_REQUEST_ERRORS'
export const CLEAR_SESSION_ERRORS = 'CLEAR_REQUEST_ERRORS'

// requests
export const RECEIVE_REQUESTS = 'RECEIVE_REQUESTS'
export const ADD_REQUEST = 'ADD_REQUEST'
export const UPDATE_REQUEST = 'UPDATE_REQUEST'
export const DELETE_REQUEST = 'DELETE_REQUEST'
export const UPDATE_REQUEST_ERRORS = 'UPDATE_REQUEST_ERRORS'
export const CLEAR_REQUEST_ERRORS = 'CLEAR_REQUEST_ERRORS'
